# Fixed Configuration Settings
random_seed: 42
device: "mps" # Options: "cuda" (for GPU) or "cpu"
disable_progress_bar: false # Set to true to hide tqdm progress bars during training/validation

# Model Configuration
model_name: "ABMIL" # Currently supports "ABMIL"
num_of_classes: 3 # Number of output classes 
feature_dim: 1536 # Dimension of the input instance embeddings

# Data Configuration
metadata_path: "example_data/TCGA-LGG/training_metadata.csv" # Path to your CSV/Excel file with 'slide_id' and 'label'
feature_dir: "data/features/uni/TCGA/TCGA-LGG" # Path to the directory containing SLIDE_ID.h5 feature files
num_workers: 0 # Number of subprocesses to use for data loading (set to 0 for debugging)

# Validation Schedule
validation_rate: 100 # Perform validation every N training batches

# Class Weights (optional)
# Uncomment and modify the weights below to handle class imbalance
# class_weights: [1.0, 2.29, 2.0] # Optimal weights for your distribution: Class 0=16, Class 1=7, Class 2=8
# The length should match num_of_classes
# Higher weights = higher penalty for misclassifying that class

# Weighted Sampler (alternative to class weights)
# Set to true to use WeightedRandomSampler instead of class weights
# This balances the data during sampling rather than in the loss function
use_weighted_sampler: false

experiment_name: "TCGA-LGG"
comet_api_key: ""