
# paths
wsi_dir: "example_data/TCGA-LGG/slides"
coordinates_dir: "example_data/TCGA-LGG/coordinates/patches"
wsi_meta_data_path: "example_data/TCGA-LGG/coordinates/process_list_autogen.csv"
features_dir: "example_data/TCGA-LGG/features/resnet"


device: "mps"
patch_batch_size: 64
num_workers: 0 # Recommended to set to 0 

#model configs
model_name: "ResNet50"
hf_token: ""

#log level
log_level: "INFO"

#disable progress bar
disable_progress_bar: False
