
# paths
wsi_dir: "data/TCGA-LGG/raw_data_part1/wsi"
coordinates_dir: "data/TCGA-LGG/processed_data_part1/wsi/patches"
wsi_meta_data_path: "data/TCGA-LGG/processed_data_part1/wsi/process_list_autogen.csv"
features_dir: "data/TCGA-LGG/processed_data_part1/wsi/features/resnet"


device: "cpu"
patch_batch_size: 64
num_workers: 0 # Recommended to set to 0 

#model configs
model_name: "resnet50"
hf_token: ""

#log level
log_level: "INFO"

#disable progress bar
disable_progress_bar: False
